project:
  type: website

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - href: /index.html
        text: NLTK-NOTES
      - href: /00_core.html
        text: ABOUT
      - text: "FEVZİ KILAS"
        href: https://fevzikilas.tech
    right:
      - icon: github
        menu:
          - text: Main
            href:  https://github.com/fevzikilas
          - text: Report a Bug
            href:  https://github.com/fevzikilas/nltk-notes/issues/new
      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/fevzikilas/
  sidebar:
    style: floating

     


metadata-files: [nbdev.yml, sidebar.yml]