# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nltk-notes',
                'doc_host': 'https://fevzikilas.github.io',
                'git_url': 'https://github.com/fevzikilas/nltk-notes',
                'lib_path': 'nltk_notes'},
  'syms': {'nltk_notes.core': {'nltk_notes.core.foo': ('core.html#foo', 'nltk_notes/core.py')}}}
